### ISSUE TITLE
🧐 Handle parsing and error handling

### ISSUE THREAD

**Issue by Thomaltarix** [Thomaltarix/Wolfram#3]
# :white_check_mark: What's needed
Collect the data from the command line and handle the errors from it.

The options in the command line can be
- [x] `--rule XX` Defines the ruleset to use (the `30`, `90` and `110` are required) (No default value, this option is mandatory)
- [x] `--start XX` Defines the generation number at which to start the display (Default is `0`)
- [x] `--lines XX` Defines the numbers of lines to display (Default is infinite)
- [x] `--window XX` Defines the number of cell to display on each line (width) (Default is `80`) (If even, the central cell is displayed in the next cell on the right)
- [x] `--move XX` Defines a translation to apply to the window (X > 0 -> translate to the right, X < 0 -> translate to the left)

If no option or invalid options are provided, the 84 error code must be returned with an usage message
(eventually accompagned with an explicite error message of your choice)

## 📋 Subtasks
- [x] Create data structures to stock the data
- [x] Collect the given options
- [x] Handle the errors in the command line
